package db

import "context"

// RetainFederationEvents combines admitted source events with the exact events
// generated by their transaction. Generated peer-project audit events never
// pass through a source-project rediscovery filter.
func RetainFederationEvents(ctx context.Context, ids []string, produced []Event, fetch func(context.Context, []string) ([]Event, error)) ([]string, []Event, error) {
	retained := make(map[string]Event, len(produced))
	seen := make(map[string]bool, len(ids))
	ordered := make([]string, 0, len(ids)+len(produced))
	for _, id := range ids {
		if !seen[id] {
			seen[id] = true
			ordered = append(ordered, id)
		}
	}
	for _, event := range produced {
		retained[event.UID] = event
		if !seen[event.UID] {
			seen[event.UID] = true
			ordered = append(ordered, event.UID)
		}
	}
	var events []Event
	for _, id := range ordered {
		if event, ok := retained[id]; ok {
			events = append(events, event)
			continue
		}
		source, err := fetch(ctx, []string{id})
		if err != nil {
			return nil, nil, err
		}
		events = append(events, source...)
	}
	return ordered, events, nil
}
